ALTER TABLE public.coletas
  ADD COLUMN IF NOT EXISTS rota_codigo TEXT,
  ADD COLUMN IF NOT EXISTS rota_id UUID REFERENCES public.rotas(id) ON DELETE SET NULL;

ALTER TABLE public.cdfs
  ADD COLUMN IF NOT EXISTS enviado BOOLEAN NOT NULL DEFAULT false;